### ISSUE TITLE
Can you provide me with pytorch code?

### ISSUE THREAD

**Issue by superYuezhang** [HaoXu-Work/FINet#2]
Your article is worth learning, so I want to read the code of your pytorch version. Can you provide me with a copy?
The email address is: yzhang9898@163.com

**Comment by hxwork** [comment]
Hi,

Thanks for your interest. We will release the Pytorch implementation in a few days (before the mid of June).

**Comment by superYuezhang** [comment]
Thank you for your reply and look forward to your code coming online as soon as possible.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月27日(星期五) 下午5:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hxwork/FINet_Pytorch] Can you provide me with pytorch code? (Issue #2)





 
Hi,
 
Thanks for your interest. We will release the Pytorch implementation in a few days (before the mid of June).

**Comment by 2848385707** [comment]
Can I still get the pyTorch code now？

**Comment by superYuezhang** [comment]
> Can I still get the pyTorch code now？

No, so far, I still haven't got the code.

**Comment by 2848385707** [comment]
> > Can I still get the pyTorch code now？
> 
> No, so far, I still haven't got the code.
Thank you for your reply and look forward to your code coming online as soon as possible.

**Comment by hxwork** [comment]
Hi all,

Sorry for the late update. I have made the code available.
