### ISSUE TITLE
not found shape_names.txt

### ISSUE THREAD

**Issue by 2848385707** [HaoXu-Work/FINet#3]
if I want to run training in OS_data,but it have a error:not such file "shape_names.txt”

**Comment by hxwork** [comment]
Hi,

You can find "shape_names.txt” in the TS_data.zip. If you haven't downloaded this zip file, you can manually create this file, and put the following texts in it.
```
airplane
bathtub
bed
bench
bookshelf
bottle
bowl
car
chair
cone
cup
curtain
desk
door
dresser
flower_pot
glass_box
guitar
keyboard
lamp
laptop
mantel
monitor
night_stand
person
piano
plant
radio
range_hood
sink
sofa
stairs
stool
table
tent
toilet
tv_stand
vase
wardrobe
xbox
```
