### ISSUE TITLE
Visualization of point cloud registration results

### ISSUE THREAD

**Issue by wh22920** [HaoXu-Work/FINet#4]
Can you provide the point cloud visualization code for the point cloud registration results? such as figure 4 in the paper.The email address is: 2609358440@qq.com

**Comment by hxwork** [comment]
A Python package named Open3D is helpful for visualization.

**Comment by wh22920** [comment]
Sorry to bother you again, thank you for your last answer. I am able to use Open3D to visualize a single point cloud, but I still cannot visualize the results before and after point cloud registration. Do I need to modify evaluate.py? I hope you can provide more detailed guidance or provide code, which can also be done through 2609358440@qq.com Contact me.
